# Mod04 Using NumPy Array

In [1]:
import numpy as np
import pandas as pd

In [2]:
np.__version__

'1.19.3'

## NumPy indexing and slicing

In [3]:
# print entire array, element 0, element 1, last element.
ar = np.arange(5); print(ar); ar[0], ar[1], ar[-1]
# !!!用print會誤以為是list

[0 1 2 3 4]


(0, 1, 4)

In [11]:
# Reverse array using ::-1 idiom
ar=np.arange(5); ar[::-1]

array([4, 3, 2, 1, 0])

In [30]:
ar = np.array([[2,3,4],[9,8,7],[11,12,13]]); ar

array([[ 2,  3,  4],
       [ 9,  8,  7],
       [11, 12, 13]])

In [31]:
ar[2,0]  # row major

11

In [32]:
ar[1,1]=5; ar

array([[ 2,  3,  4],
       [ 9,  5,  7],
       [11, 12, 13]])

In [49]:
ar[::2,::2]
 

array([[ 2,  4],
       [11, 13]])

In [33]:
# Retrieve row 2
ar[2]

array([11, 12, 13])

In [35]:
# 與上面同義，row2 all data
ar[0,:]

array([2, 3, 4])

In [36]:
# Retrieve column 1
# 可以抓出column 直行的所有資料!
ar[:,0]

array([ 2,  9, 11])

Assignment and slicing can be combined as shown in the following code snippet:

In [73]:
ar=2*np.arange(6); ar  # vecorized expression

array([ 0,  2,  4,  6,  8, 10])

In [74]:
ar

array([ 0,  2,  4,  6,  8, 10])

In [60]:
ar[:2]=99; ar

array([99, 99,  4,  6,  8, 10])

In [75]:
# ones是浮點，但在這邊被截掉
ar[2:]=np.ones(4);ar

array([0, 2, 1, 1, 1, 1])

### Fancy Indexing

In [84]:
#  與上面等義，產出低於100以下的整數，並用RandomState固定
rand = np.random.RandomState(90)
x = rand.randint(100, size=10)
x

array([91, 29, 31, 67, 39, 68, 58, 37, 18, 74])

In [85]:
#  與上面等義，產出低於100以下的整數，並用seed固定
np.random.seed(90)
y = np.random.randint(100, size=10)
y

array([91, 29, 31, 67, 39, 68, 58, 37, 18, 74])

In [86]:
# access three different elements,return list
[x[3], x[7], x[2]]

[67, 37, 31]

In [92]:
%%timeit
# access three different elements,return list
np.array([x[3], x[7], x[2]])

1.35 µs ± 43.8 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [93]:
#fancy index. return numpy array
x[[0,-1,2]]

array([91, 74, 31])

In [90]:
%%timeit
#fancy index
x[[3,7,2]]

1.16 µs ± 3.49 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


#### Access rows in 2d array

In [94]:
arr = np.empty((8, 4)) # 8*4，填滿0的陣列 
for i in range(8):  # 由第一列往第八列依序往下填
    arr[i] = i

In [95]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [96]:
arr[[4, 3, 0, 6]]  # 取得各欄。  只能抓欄不能抓列。

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

## Array masking  遮罩

In [97]:
np.random.seed(10)
ar=np.random.randint(0,25,10); ar

array([ 9,  4, 15,  0, 17, 16, 17,  8,  9,  0])

In [98]:
evenMask=(ar%2==0); evenMask  

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [99]:
evenNums=ar[evenMask]; evenNums

array([ 4,  0, 16,  8,  0])

In [105]:
# 寫在一起，仍為兩段運算
oddNums = ar[ar%2!=0] ; oddNums

array([ 9, 15, 17, 17,  9])

To eliminate missing values

In [128]:
ar=np.array(['Hungary','Nigeria',
'Guatemala','','Poland','','Japan','']); ar

array(['Hungary', 'Nigeria', 'Guatemala', '', 'Poland', '', 'Japan', ''],
      dtype='<U9')

In [117]:
# 無所謂速度快慢，因為無數值，本來就慢
ar[ar=='']='USA' ; ar

array(['Hungary', 'Nigeria', 'Guatemala', 'USA', 'Poland', 'USA', 'Japan',
       'USA'], dtype='<U9')

In [129]:
#  字元超出陣列範圍時無效，直接捨去
ar[ar=='']='THIS IS A BOOK ' ; ar

array(['Hungary', 'Nigeria', 'Guatemala', 'THIS IS A', 'Poland',
       'THIS IS A', 'Japan', 'THIS IS A'], dtype='<U9')

## Copies and views

<b>Modifying view modifies original array</b>

In [130]:
ar1=np.arange(12); ar1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [131]:
ar2=ar1[::2]; ar2

array([ 0,  2,  4,  6,  8, 10])

In [134]:
ar2[1]=-1; ar1  # change chile array(vision),then parent array changed 

array([ 0,  1, -1,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [140]:
# check either same memory
np.may_share_memory(ar1,ar2)

True

<b>Use np.copy to force a copy</b><br>

In [135]:
ar=np.arange(8); ar

array([0, 1, 2, 3, 4, 5, 6, 7])

In [136]:
arc=ar[:3].copy(); arc  # if copy, create new array,independent with original array 

array([0, 1, 2])

In [137]:
arc[0]=-1; arc

array([-1,  1,  2])

In [138]:
ar

array([0, 1, 2, 3, 4, 5, 6, 7])

In [139]:
np.may_share_memory(arc,ar)

False