# Mod06 NumPy Advanced Operations

# Operations

## Advanced Operations

In [2]:
import numpy as np
import pandas as pd

## Statistical operators

In [3]:
arr=np.array([9, 4, 1, 2, 9])
arr.mean()

5.0

In [4]:
arr.std()

3.40587727318528

In [5]:
np.random.seed(10)
ar=np.random.randint(0,10, size=(4,5)); ar

array([[9, 4, 0, 1, 9],
       [0, 1, 8, 9, 0],
       [8, 6, 4, 3, 0],
       [4, 6, 8, 1, 8]])

In [ ]:
ar.mean()

In [6]:
ar.mean(axis=0)

array([5.25, 4.25, 5.  , 3.5 , 4.25])

In [7]:
ar.mean(axis=1)

array([4.6, 3.6, 4.2, 5.4])

In [8]:
ar.var(axis=1) #across columns

array([14.64, 16.24,  7.36,  7.04])

In [9]:
# 累計式加總，例如各銷售量月
ar.cumsum()

array([ 9, 13, 13, 14, 23, 23, 24, 32, 41, 41, 49, 55, 59, 62, 62, 66, 72,
       80, 81, 89])

In [10]:
# 4個產品累計銷售量
ar.cumsum(axis=1)

array([[ 9, 13, 13, 14, 23],
       [ 0,  1,  9, 18, 18],
       [ 8, 14, 18, 21, 21],
       [ 4, 10, 18, 19, 27]])

## Logical operators

In [19]:
np.random.seed(100)
ar=np.random.randint(1,10, size=(4,4)); ar

array([[9, 9, 4, 8],
       [8, 1, 5, 3],
       [6, 3, 3, 3],
       [2, 1, 9, 5]])

In [25]:
ar<6

array([[False, False,  True, False],
       [False,  True,  True,  True],
       [False,  True,  True,  True],
       [ True,  True, False,  True]])

In [24]:
np.sum(ar<6)

10

In [26]:
np.sum(ar<6,axis=1)

array([1, 3, 3, 3])

In [29]:
%%timeit
np.count_nonzero(ar)

469 ns ± 1.72 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [28]:
%%timeit
np.sum(ar!=0)

3.71 µs ± 61.9 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [14]:
ar=np.array([9, 9, 4, 8,14])
np.any((ar%7)==0)

True

In [15]:
np.all(ar<11)

False

In [16]:
x=np.arange(10);x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
# numpy的'and' 要用&符號表達
x[ (x>4) & (x<8)]
 

array([5, 6, 7])

In [17]:
x[ (x>4)and(x<8)]
# Error: The truth value of an array with more than one element is ambiguous.
# Use a.any() or a.all()

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

## Broadcasting

In [30]:
ar=np.ones([3,2]); ar

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [31]:
ar2=np.array([2,3]); ar2

array([2, 3])

In [ ]:
ar+ar2

<b>Row expansion</b>

In [34]:
ar1 = np.array([[0, 0, 0],
                [1, 1, 1],
                [2, 2, 2],
                [3, 3, 3]])
 

In [35]:
ar1.shape

(4, 3)

In [37]:
ar2=np.array([1,2,3])
ar2

array([1, 2, 3])

In [36]:
ar2.shape

(3,)

In [38]:
ar1+ar2

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

<b>Column expansion</b>

In [39]:
ar1
# (4,3)

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [40]:
ar2=np.array([1,2,3,4])
ar3=ar2.reshape((4,1))
ar3
# (4,1)==>(4,3)

array([[1],
       [2],
       [3],
       [4]])

In [41]:
ar1+ar3

array([[1, 1, 1],
       [3, 3, 3],
       [5, 5, 5],
       [7, 7, 7]])

In [50]:
arr1=np.arange(6)
arr1
#(6,)

array([0, 1, 2, 3, 4, 5])

In [51]:
arr2=np.arange(8) 
arr2
#(8,)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [49]:
#　無法拓展
arr1+arr2


ValueError: operands could not be broadcast together with shapes (6,1) (8,1) 