# Mod03 Create NumPy Array

In [1]:
import numpy as np
import pandas as pd

In [2]:
np.__version__

'1.19.3'

In [3]:
pd.__version__

'1.1.4'

In [11]:
# reference handbook p.38
lst = [1,2,3]


In [16]:
id(lst)

139815916083840

In [17]:
id(lst[0]) # 0x310718

9784864

In [18]:
id(lst[1]) # 0x310748 

9784896

In [19]:
id(lst[2]) # 0x310730

9784928

## NumPy array creation via numpy.array
NumPy arrays can be created via the numpy.array constructor directly

In [22]:
ar1 = np.array([0,1,2,3]) # 1 dimensional array



In [5]:
ar2=np.array([[0,3,5],[2,8,7]]) # 2D array

In [21]:
ar1

array([0. , 1.1, 2. , 3. ])

In [7]:
ar2 # row major

array([[0, 3, 5],
       [2, 8, 7]])

In [23]:
# shape
ar2.shape

(2, 3)

In [24]:
# ndim
ar2.ndim

2

In [25]:
# dtype
ar2.dtype

dtype('int64')

In [26]:
type(ar2)
# numpy.ndarray

numpy.ndarray

In [27]:
ar2.size

6

## NumPy array creation via numpy.arange
ndarray.arange is the NumPy version of Python's range function

In [28]:
#ar3=np.arange(12); ar3
ar3=np.arange(12)
ar3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [29]:
# start, end (exclusive)
#ar4=np.arange(3,10,3); ar4
ar4=np.arange(3,10,3)
ar4

array([3, 6, 9])

In [30]:
ar5=np.arange(5,10)
ar5  

array([5, 6, 7, 8, 9])

In [31]:
type(ar5)  

numpy.ndarray

## NumPy datatypes
Specify the type of contents of a numeric array by using the dtype parameter

In [40]:
#ar=np.array([2,-1,6,3],dtype='float'); ar
ar=np.array([2,-1,6,3],dtype='float');
ar

array([ 2., -1.,  6.,  3.])

In [41]:
ar.dtype

dtype('float64')

In [42]:
ar=np.array([2,4,6,8]); ar.dtype

dtype('int64')

In [43]:
ar=np.array([2.,4,6,8]); ar.dtype

dtype('float64')

In [44]:
sar=np.array(['Goodbye','Welcome','Tata','Goodnight']); sar.dtype
# unicode
# 9 maximum  

dtype('<U9')

In [45]:
# NunPy有布林的資料型態
bar=np.array([True, False, True]); bar.dtype

dtype('bool')

In [47]:
# 自動轉型
f_ar = np.array([3,-2,8.18])
f_ar

array([ 3.  , -2.  ,  8.18])

In [48]:
# 強制轉型，小數點自動捨棄
f_ar.astype(int)

array([ 3, -2,  8])

## NumPy array creation via numpy.linspace
ndarray.linspace generates linear evenly spaced elements between the start and the end

In [50]:
# args - start element,end element, number of elements
#ar6=np.linspace(0,2.0/3,4); ar5
ar6=np.linspace(0,2.0/3,4)
ar6

array([0.        , 0.22222222, 0.44444444, 0.66666667])

## NumPy array via various other functions
These functions include numpy.zeros, numpy.ones, numpy.eye, nrandom.rand,
numpy.random.randn, and numpy.empty

### numpy.ones

In [64]:
# Produces 2x3x2 array of 1's.  
# all float
ar7=np.ones((2,5,3)); ar7

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

### numpy.zeros

In [63]:
# Produce 4x2 array of zeros.
ar8=np.zeros((3,8)); ar8

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

### numpy.eye

In [103]:
# Produces identity matrix
ar9 = np.eye(5,k=-1); ar9

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

### numpy.empty

In [59]:
ar13=np.empty((3,2)); ar13

array([[1.28135174e-316, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000]])

### numpy.random.rand

In [101]:
# Using the rand, randn functions
# rand(m) produces an array of the given shape 
# with uniformly distributed random numbers over [0,1)
np.random.seed(200) # Set seed > all num is same   
ar11=np.random.rand(3 ); ar11
print(ar11)
print(sum(ar11))

[0.94763226 0.22654742 0.59442014]
1.7685998223745258


In [108]:
# randn(m) produces m normally distributed (Gaussian) random numbers
# no seed
ar12=np.random.randn(5); ar12

array([], shape=(0, 5, 15), dtype=float64)

In [107]:
# 平均是10，標準差為1，常態分布4*4陣列
ar13=np.random.normal(10,1, (3,5)); ar13

array([[ 8.97747962,  9.24047391, 10.30337099, 10.23044079, 10.57091681],
       [ 8.8409775 ,  8.52427068, 10.05436857, 10.42867475, 12.16658548],
       [ 8.45727183, 10.85534664, 10.32714315, 10.58067026,  9.87967566]])

### 

In [112]:
# range 0-5，2*5 Array
ar14=np.random.randint(0,5,(2,5)); ar14

array([[2, 0, 2, 4, 3],
       [2, 1, 4, 0, 2]])